# Generated by Django 4.0.3 on 2022-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Marka & Model')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Kapasite')),
                ('image', models.ImageField(default='', upload_to='media/', verbose_name='Resim')),
                ('car_model_year', models.IntegerField(blank=True, null=True, verbose_name='Üretim yılı')),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.IntegerField(verbose_name='Fiyat')),
                ('gearbox', models.CharField(choices=[('M', 'MANUEL'), ('A', 'AUTOMATIC')], default='M', max_length=25, verbose_name='Vites')),
                ('is_active', models.BooleanField(default=True, help_text='Anasayfada görünürlüğünü değiştir', verbose_name='Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('-created_at',),
            },
        ),
    ]
