# Generated by Django 4.0.3 on 2022-03-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_header_offer_alter_car_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.CreateModel(
            name='CarImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload an image', upload_to='images/', verbose_name='Resim')),
                ('alt_text', models.CharField(blank=True, help_text='Please add an alternative text', max_length=255, null=True, verbose_name='Alt text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu tarih')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='homepage.car')),
            ],
            options={
                'verbose_name': 'Car image',
                'verbose_name_plural': 'Car images',
            },
        ),
    ]
