# Generated by Django 4.0.3 on 2022-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_car_image_carimagetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimagetable',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
