# Generated by Django 4.0.3 on 2022-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_carimagetable_is_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gasoline',
            field=models.CharField(choices=[('D', 'DIZEL'), ('B', 'BENZIN')], default='D', max_length=25, verbose_name='Benzin / Dizel'),
        ),
    ]
